image: gcc

before_script:
  - apt-get update -qq -y && apt-get install -qq -y cmake libpcre2-8-0 libpcre2-dev libsdl2-ttf-dev zlib1g-dev
      libpcap-dev ninja-build

stages:
  - build

simh:
  stage: build
  script: 
    - ./cmake-builder.sh --config Release --flavor unix  --parallel --clean
    - ./cmake-builder.sh --config Debug   --flavor unix  --parallel --clean
    - ./cmake-builder.sh --config Release --flavor ninja --parallel --clean
    - ./cmake-builder.sh --config Debug   --flavor ninja --parallel --clean
