image: gcc

before_script:
  - apt-get update -qq -y && apt-get install -y cmake libpcre2-8-0 libpcre2-dev libsdl2-ttf-dev zlib1g-dev ninja-build

stages:
  - build

simh:
  stage: build
  script: 
    - mkdir cmake-unix
    - cd cmake-unix
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DWITH_NETWORK:Bool=Off -DWITH_PCAP:Bool=Off -DWITH_SLIRP:Bool=Off ..
    - cmake --build . --config Release --parallel -- -j 10
    - ctest -C Release
    - cd ..
    - mkdir cmake-ninja
    - cd cmake-ninja
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DWITH_NETWORK:Bool=Off -DWITH_PCAP:Bool=Off -DWITH_SLIRP:Bool=Off ..
    - cmake --build . --config Release --parallel -- -j 10
    - ctest -C Debug
  
# run tests using the binary built before
test:
  stage: test
  script:
    - "[ -d cmake-unix ] && (cd cmake-unix; ctest -C Release)"
    - "[ -d cmake-ninja ] && (cd cmake-ninja; ctest -C Release)"
